name: Update Statistics and Deploy

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - main  # Run on pushes to main branch
    paths-ignore:
      - 'config.js'  # Ignore pushes that only change config.js to avoid infinite loops

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      
      - name: Ensure clean working directory
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git reset --hard origin/main
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Update repository statistics
        run: |
          python .github/scripts/extract_metrics_from_xml.py
          
      - name: Commit and push changes
        id: push
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          # Stage changes
          git add config.js
          
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "changes_pushed=false" >> $GITHUB_OUTPUT
          else
            # Pull latest changes with strategy to handle conflicts
            git pull --rebase origin main || git pull origin main
            
            # Commit changes
            git commit -m "Update repository statistics"
            
            # Push with retry logic
            MAX_RETRIES=3
            RETRY_COUNT=0
            
            while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
              if git push; then
                echo "Successfully pushed changes"
                echo "changes_pushed=true" >> $GITHUB_OUTPUT
                break
              else
                RETRY_COUNT=$((RETRY_COUNT+1))
                echo "Push failed, retry $RETRY_COUNT of $MAX_RETRIES"
                
                if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
                  echo "Pulling latest changes before retrying..."
                  git pull --rebase origin main || git pull origin main
                  sleep 5
                fi
              fi
            done
            
            if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
              echo "Failed to push after $MAX_RETRIES attempts"
              exit 1
            fi
          fi

    outputs:
      changes_pushed: ${{ steps.push.outputs.changes_pushed }}

  # This job runs if changes were pushed OR if workflow was manually triggered.
  deploy-pages:
    needs: update-stats
    if: needs.update-stats.outputs.changes_pushed == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Deploy to GitHub Pages
        run: |
          # Display the content about to be deployed
          echo "Files to be deployed:"
          ls -la
          
          # Setup git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Start fresh - delete and recreate gh-pages branch
          git checkout --orphan gh-pages
          git rm -rf .
          
          # Copy necessary files from main branch
          git checkout main -- index.html config.js app.js styles.css || echo "Failed to checkout some files"
          
          # Create a simple .nojekyll file to bypass Jekyll processing
          touch .nojekyll
          
          # Commit and push to gh-pages branch
          git add --all
          git commit -m "Update GitHub Pages content" || echo "No changes to commit"
          git push -f origin gh-pages

