name: Update Repository Statistics

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - main  # Run on pushes to main branch
    paths-ignore:
      - 'config.js'  # Ignore pushes that only change config.js to avoid infinite loops

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Update repository statistics
        run: |
          python .github/scripts/update_stats.py
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add config.js
          git commit -m "Update repository statistics [skip ci]" || echo "No changes to commit"
          git push
