name: Update Repository Statistics

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - main  # Run on pushes to main branch
    paths-ignore:
      - 'config.js'  # Ignore pushes that only change config.js to avoid infinite loops

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Update repository statistics
        run: |
          python .github/scripts/update_stats.py
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add config.js
          git commit -m "Update repository statistics [skip ci]" || echo "No changes to commit"
          git push

  # This job runs after update-stats completes successfully
  deploy-pages:
    needs: update-stats
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required for this job
    permissions:
      pages: write
      id-token: write
      contents: write
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main  # Ensure we have the latest changes
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Deploy directly to gh-pages branch
        run: |
          # Display the content we're about to deploy
          echo "Files to be deployed:"
          ls -la
          
          # Verify index.html exists
          if [ -f "index.html" ]; then
            echo "✅ Found index.html"
          else
            echo "❌ index.html missing! Creating empty placeholder."
            echo "<!DOCTYPE html><html><head><title>Sanity Test Reports Hub</title></head><body><h1>Sanity Test Reports Hub</h1><p>No content available.</p></body></html>" > index.html
          fi
          
          # Setup git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Create a new branch for gh-pages or use the existing one
          git checkout gh-pages 2>/dev/null || git checkout -b gh-pages
          
          # Copy necessary files from main branch
          git checkout main -- index.html config.js || echo "Failed to checkout files"
          if [ -f "app.js" ]; then
            git checkout main -- app.js
          else
            echo "// App.js file for Sanity Test Hub" > app.js
            git add app.js
          fi
          
          # Commit and push to gh-pages branch
          git add index.html config.js app.js
          git commit -m "Update GitHub Pages content" || echo "No changes to commit"
          git push -f origin gh-pages
